# font_family      Nunito
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size        11.0

window_padding_width 12

# Pastel Purple Theme Palette
foreground            #CDD6F4
background            #1E1E2E
selection_foreground  #1E1E2E
selection_background  #F5E0DC

# Cursor
cursor                #F5E0DC
cursor_text_color     #1E1E2E

# Colors
color0  #45475A
color8  #585B70
color1  #F38BA8
color9  #F38BA8
color2  #A6E3A1
color10 #A6E3A1
color3  #F9E2AF
color11 #F9E2AF
color4  #89B4FA
color12 #89B4FA
color5  #CBA6F7
color13 #CBA6F7
color6  #94E2D5
color14 #94E2D5
color7  #BAC2DE
color15 #A6ADC8

# BEGIN_KITTY_FONTS
font_family      family="Spline Sans Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS